from __future__ import annotations

import re
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path


TEMPLATE_ROOT = Path(__file__).resolve().parents[1]

# `uses:` as a YAML key, anchored to the start of its line. Unanchored, this
# also matches the pin check's own grep pattern, which is a shell string
# inside a `run:` block that happens to contain the word.
USES = re.compile(r"^\s*-?\s*uses:\s*(\S+)", re.MULTILINE)

# Every question the template asks, answered. The template carries no defaults
# — a default is an answer nobody gave — so a generation that omits one fails,
# and this suite answers every question like any other caller.
ANSWERS = {
    "project_name": "example-ui",
    "project_description": "An example package generated by the project template.",
    "github_owner": "example-owner",
    "keywords": "example, template",
    "categories": "development-tools",
    "rust_toolchain": "1.97.1",
    "rust_version": "1.92",
    "license_expression": "MIT",
    "copyright_holder": "Example Holder",
    "copyright_year": "2026",
    "unsafe_policy": "deny",
    "clippy_pedantic": "true",
    # The opt-in verification surfaces, all on: the suite's job is to check
    # what the template can generate, and `yes` is the answer that generates
    # something to check. The opt-out is what the dedicated test renders.
    "openssf_scorecard": "true",
    "mutation_testing": "true",
    "fuzzing": "true",
}


def snapshot_without_git(destination: Path) -> Path:
    """Copies the template to `destination`, leaving `.git` behind.

    Copier reads a local template that is a Git repository at its latest tag,
    not as it sits on disk — correct for someone generating a project, and
    wrong for a test suite, which would then be checking the last release
    instead of the change being made. Without a `.git` directory there is no
    tag to prefer and Copier reads the files.

    `symlinks=True` because `AGENTS.md` is one, and the suite checks that it
    still is on the other side.
    """
    shutil.copytree(
        TEMPLATE_ROOT,
        destination,
        dirs_exist_ok=True,
        ignore=shutil.ignore_patterns(".git", "__pycache__"),
        symlinks=True,
    )
    return destination


class TemplateGenerationTests(unittest.TestCase):
    template: Path

    @classmethod
    def setUpClass(cls) -> None:
        cls._snapshot = tempfile.TemporaryDirectory()
        cls.addClassCleanup(cls._snapshot.cleanup)
        cls.template = snapshot_without_git(Path(cls._snapshot.name))

    def render(self, *, project_kind: str, **overrides: str) -> Path:
        temporary = tempfile.TemporaryDirectory()
        self._temporary_directories.append(temporary)
        self.addCleanup(temporary.cleanup)
        destination = Path(temporary.name)
        answers = ANSWERS | {"project_kind": project_kind} | overrides
        arguments = []
        for question, answer in answers.items():
            arguments += ["--data", f"{question}={answer}"]
        subprocess.run(
            [
                "copier",
                "copy",
                "--trust",
                "--defaults",
                *arguments,
                str(self.template),
                str(destination),
            ],
            check=True,
        )
        return destination

    def setUp(self) -> None:
        self._temporary_directories: list[tempfile.TemporaryDirectory[str]] = []

    def paths_in(self, generated: Path) -> set[str]:
        return {
            path.relative_to(generated).as_posix()
            for path in generated.rglob("*")
        }

    def test_published_library_exposes_the_approved_project_surface(self) -> None:
        generated = self.render(project_kind="published_library")
        expected_paths = {
            ".copier-answers.yml",
            ".github/dependabot.yml",
            ".github/workflows/ci.yml",
            ".github/workflows/commits.yml",
            ".github/workflows/dco.yml",
            ".github/workflows/minimal-versions.yml",
            ".github/workflows/msrv.yml",
            ".github/workflows/release-plz.yml",
            ".github/workflows/release.yml",
            ".github/workflows/scorecard.yml",
            ".github/workflows/mutants.yml",
            ".github/workflows/semver.yml",
            ".github/workflows/security.yml",
            ".github/workflows/template-update.yml",
            ".editorconfig",
            "fuzz/Cargo.toml",
            "fuzz/fuzz_targets/api.rs",
            "fuzz/.gitignore",
            ".github/ISSUE_TEMPLATE/bug.yml",
            ".github/PULL_REQUEST_TEMPLATE.md",
            ".gitignore",
            ".config/nextest.toml",
            "AGENTS.md",
            "CHANGELOG.md",
            "CLAUDE.md",
            "CONTRIBUTING.md",
            "Cargo.lock",
            "Cargo.toml",
            "LICENSE",
            "README.md",
            "SECURITY.md",
            "clippy.toml",
            "deny.toml",
            "fixtures/consumer/Cargo.toml",
            "fixtures/consumer/Cargo.lock",
            "fixtures/consumer/src/main.rs",
            "tests/public_api.rs",
            "release-plz.toml",
            "taplo.toml",
            "rust-toolchain.toml",
            "xtask/Cargo.toml",
            "xtask/src/main.rs",
        }

        self.assertTrue(expected_paths.issubset(self.paths_in(generated)))
        self.assertTrue((generated / "AGENTS.md").is_symlink())
        self.assertEqual((generated / "AGENTS.md").readlink(), Path("CLAUDE.md"))
        self.assertIn(
            'rust-version = "1.92"',
            (generated / "Cargo.toml").read_text(encoding="utf-8"),
        )

    def test_workspace_application_generates_runnable_app_and_xtask(self) -> None:
        generated = self.render(project_kind="workspace_app")

        self.assertTrue((generated / "apps/example-ui/src/main.rs").is_file())
        self.assertTrue((generated / "xtask/src/main.rs").is_file())
        self.assertFalse((generated / "src/lib.rs").exists())

        # What `dist generate` needs and cannot infer. Asserted on the manifest as
        # well as through dist itself, because the dist test skips wherever
        # dist is not installed and this is the half that explains why.
        manifest = (generated / "apps/example-ui/Cargo.toml").read_text(
            encoding="utf-8"
        )
        self.assertIn("repository.workspace = true", manifest)
        self.assertIn("dist = true", manifest)

        subprocess.run(
            ["cargo", "xtask", "check"],
            cwd=generated,
            check=True,
        )

    def test_a_generated_project_passes_its_own_gate(self) -> None:
        """`cargo xtask ci` is what a generated project asks of every change,
        including the first one. A template that hands a project a gate it
        cannot pass has handed it a problem to fix before it can start.

        This is where rendering shows: `cargo fmt --check` fails on a blank
        line a Jinja block left behind, and `cargo deny` fails on a member
        crate whose manifest names no license.
        """
        for project_kind in ("published_library", "workspace_app"):
            with self.subTest(project_kind=project_kind):
                generated = self.render(project_kind=project_kind)
                subprocess.run(
                    ["cargo", "xtask", "ci"],
                    cwd=generated,
                    check=True,
                )

                # And the lint task again with a dev-dependency in the tree:
                # `cargo hack --no-dev-deps` hands cargo a manifest without
                # that table, and the flags beside it must tolerate the
                # re-resolve. The skeleton has no dev-dependencies, which is
                # exactly how an incompatible `--locked` once shipped
                # unnoticed. itoa, because it has none of its own.
                subprocess.run(
                    ["cargo", "add", "--dev", "itoa@1", "--package", "example-ui"],
                    cwd=generated,
                    check=True,
                )
                # Anchored where a dev-dependency is actually visible: an
                # integration test for the library, a `#[cfg(test)]` module
                # for the binary — `use` in plain binary code cannot see it.
                if project_kind == "published_library":
                    anchor, snippet = (
                        "tests/public_api.rs",
                        "\n// Anchors the dev-dependency for cargo-machete.\n"
                        "use itoa as _;\n",
                    )
                else:
                    anchor, snippet = (
                        "apps/example-ui/src/main.rs",
                        "\n// Anchors the dev-dependency for cargo-machete.\n"
                        "#[cfg(test)]\n"
                        "mod dev_dependency_anchor {\n"
                        "    use itoa as _;\n"
                        "}\n",
                    )
                with open(generated / anchor, "a", encoding="utf-8") as file:
                    file.write(snippet)
                subprocess.run(
                    ["cargo", "xtask", "lint"],
                    cwd=generated,
                    check=True,
                )

    def test_all_supported_profile_combinations_render(self) -> None:
        for project_kind in ("published_library", "workspace_app"):
            for unsafe_policy in ("deny", "scoped"):
                for clippy_pedantic in ("true", "false"):
                    with self.subTest(
                        project_kind=project_kind,
                        unsafe_policy=unsafe_policy,
                        clippy_pedantic=clippy_pedantic,
                    ):
                        self.assert_profile_combination_renders(
                            project_kind, unsafe_policy, clippy_pedantic
                        )

    def assert_profile_combination_renders(
        self, project_kind: str, unsafe_policy: str, clippy_pedantic: str
    ) -> None:
        generated = self.render(
            project_kind=project_kind,
            unsafe_policy=unsafe_policy,
            clippy_pedantic=clippy_pedantic,
        )
        manifest = (generated / "Cargo.toml").read_text(encoding="utf-8")
        expected = "deny" if unsafe_policy == "deny" else "warn"
        self.assertIn(f'unsafe_code = "{expected}"', manifest)
        # Enabled whole or absent whole — the question the template asks is
        # about the group, never about individual pedantic lints.
        self.assertEqual(
            'pedantic = { level = "warn", priority = -1 }' in manifest,
            clippy_pedantic == "true",
        )
        # Miri answers a question only code allowed to write
        # `unsafe` can raise, and it costs an order of magnitude
        # in CI minutes to ask.
        self.assertEqual(
            (generated / ".github/workflows/miri.yml").exists(),
            unsafe_policy == "scoped",
        )
        # A library promises a minimum toolchain to whoever
        # depends on it; an application ships binaries and
        # promises nothing to a compiler. Each carries the release
        # path and checks that fit it, and neither the other's.
        library = project_kind == "published_library"
        paths = self.paths_in(generated)
        for path, belongs_to_a_library in (
            (".github/workflows/release.yml", True),
            (".github/workflows/msrv.yml", True),
            (".github/workflows/minimal-versions.yml", True),
            ("fixtures/consumer/Cargo.toml", True),
            ("tests/public_api.rs", True),
            ("crates/README.md", False),
            (".github/workflows/release-gate.yml", False),
            (".github/workflows/sbom.yml", False),
            ("dist-workspace.toml", False),
        ):
            self.assertEqual(
                path in paths,
                library == belongs_to_a_library,
                f"{path} in a {project_kind}",
            )

    def test_the_optional_verification_surfaces_are_opt_in(self) -> None:
        """Scorecard, mutation testing and fuzzing each cost something — CI
        minutes, a public score, a directory — so each is a question, and
        `no` has to mean the file is absent rather than present and off."""
        declined = self.paths_in(self.render(
            project_kind="published_library",
            openssf_scorecard="false",
            mutation_testing="false",
            fuzzing="false",
        ))
        for path in (
            ".github/workflows/scorecard.yml",
            ".github/workflows/mutants.yml",
            "fuzz/Cargo.toml",
        ):
            self.assertNotIn(path, declined)

        # Semver checking compares against the version on crates.io and a
        # fuzz harness exercises a public API — a workspace application has
        # neither, whatever the answers say.
        application = self.paths_in(self.render(project_kind="workspace_app"))
        self.assertNotIn(".github/workflows/semver.yml", application)
        self.assertNotIn("fuzz/Cargo.toml", application)
        self.assertIn(".github/workflows/scorecard.yml", application)
        self.assertIn(".github/workflows/mutants.yml", application)

    def test_the_license_files_are_the_ones_the_expression_names(self) -> None:
        """A project carries the text of every license it offers, and no other.

        The SPDX expression in `Cargo.toml` is a promise about what a user may
        do; the files beside it are what they read to find out. One without the
        other is a project that cannot be used by anyone who checks.

        A single license is `LICENSE` — the name a reader and every tool looks
        for. Two have to be told apart, and only then are they spelled out.
        """
        mit_only = self.paths_in(self.render(
            project_kind="published_library",
            license_expression="MIT",
        ))
        self.assertIn("LICENSE", mit_only)
        self.assertNotIn("LICENSE-MIT", mit_only)
        self.assertNotIn("LICENSE-APACHE-2.0", mit_only)

        apache_only = self.render(
            project_kind="published_library",
            license_expression="Apache-2.0",
        )
        self.assertIn("LICENSE", self.paths_in(apache_only))
        self.assertNotIn("LICENSE-MIT", self.paths_in(apache_only))
        self.assertIn(
            "Apache License",
            (apache_only / "LICENSE").read_text(encoding="utf-8"),
        )

        dual = self.render(
            project_kind="workspace_app",
            license_expression="MIT OR Apache-2.0",
        )
        self.assertIn("LICENSE-MIT", self.paths_in(dual))
        self.assertIn("LICENSE-APACHE-2.0", self.paths_in(dual))
        self.assertNotIn("LICENSE", self.paths_in(dual))
        self.assertIn(
            "Copyright (c) 2026 Example Holder",
            (dual / "LICENSE-MIT").read_text(encoding="utf-8"),
        )
        self.assertIn(
            'license = "MIT OR Apache-2.0"',
            (dual / "Cargo.toml").read_text(encoding="utf-8"),
        )

    def test_nothing_generated_still_contains_jinja(self) -> None:
        """A file holding `{{ ... }}` without a `.jinja` suffix is copied
        verbatim, and the project is generated with the placeholder still in
        it. Nothing else notices: the file is valid YAML, valid Markdown, and
        wrong — an issue form linking to `github.com/owner/{{ project_name }}`
        renders and is simply a dead link.

        `${{ ... }}` is GitHub Actions' own syntax and belongs in workflows.
        """
        for project_kind in ("published_library", "workspace_app"):
            generated = self.render(project_kind=project_kind)
            for path in sorted(generated.rglob("*")):
                if not path.is_file() or path.is_symlink():
                    continue
                try:
                    text = path.read_text(encoding="utf-8")
                except UnicodeDecodeError:
                    continue
                leftovers = [
                    line
                    for line in text.splitlines()
                    if ("{{" in line.replace("${{", "") or "{%" in line)
                ]
                self.assertEqual(
                    leftovers,
                    [],
                    f"{path.relative_to(generated)} was copied without being rendered",
                )

    def test_generated_workflows_pass_actionlint(self) -> None:
        """The workflows are shipped as text and never run before a project has
        them, so nothing here would notice a broken one until a real repository
        did. Skipped rather than failed where actionlint is absent: the
        template's own CI installs it, and a contributor without it should
        still be able to run the suite."""
        if shutil.which("actionlint") is None:
            self.skipTest("actionlint is not installed")

        for project_kind in ("published_library", "workspace_app"):
            with self.subTest(project_kind=project_kind):
                generated = self.render(project_kind=project_kind)
                # actionlint wants a repository to resolve `./`-relative
                # actions and the default branch against.
                self.git(generated, "init", "--initial-branch=main")
                subprocess.run(["actionlint"], cwd=generated, check=True)

    def test_every_action_in_a_generated_project_is_pinned_to_a_commit(self) -> None:
        """A tag is a name the publisher can move; a commit is not.

        The generated project runs this check on itself, which is the point at
        which an unpinned action is found — in somebody else's repository,
        after they generated it. Ask here instead.
        """
        pinned = re.compile(r"@[0-9a-f]{40}$")
        for project_kind in ("published_library", "workspace_app"):
            with self.subTest(project_kind=project_kind):
                generated = self.render(project_kind=project_kind)
                for path in sorted((generated / ".github").rglob("*.yml")):
                    for uses in USES.findall(path.read_text(encoding="utf-8")):
                        # Local actions are this repository's own and carry no
                        # `@ref` to pin.
                        if uses.startswith("."):
                            continue
                        self.assertRegex(
                            uses,
                            pinned,
                            f"{path.relative_to(generated)} pins {uses} to a tag",
                        )

    def test_a_workspace_application_can_generate_its_release_workflow(self) -> None:
        """`dist generate` is a setup step the generated project cannot skip:
        it is what turns dist-workspace.toml into the workflow that reads it,
        and until it runs the project has a release configuration and nothing
        that runs it.

        Two things make it fail on a project nothing has touched, and both are
        invisible until somebody tries. `publish = false` says nothing goes to
        a registry, and dist reads it as "not worth building" — leaving a
        release with no binaries. And dist wants each binary's own manifest to
        name the repository, which a `[workspace.package]` entry reaches only
        where the member asks for it.

        Skipped rather than failed where dist is absent, so a contributor
        without it can still run the suite; this repository's CI installs it.
        """
        if shutil.which("dist") is None:
            self.skipTest("dist is not installed")

        generated = self.render(project_kind="workspace_app")
        # dist reads the workspace through git, and writes into `.github/`.
        self.git(generated, "init", "--initial-branch=main")
        self.git(generated, "config", "user.name", "Project Test")
        self.git(generated, "config", "user.email", "project@example.invalid")
        self.git(generated, "config", "commit.gpgsign", "false")
        self.git(generated, "add", ".")
        self.git(generated, "commit", "-m", "feat: generate project")

        subprocess.run(["dist", "generate"], cwd=generated, check=True)

        release = generated / ".github/workflows/release.yml"
        self.assertTrue(release.is_file(), "dist generate wrote no workflow")
        workflow = release.read_text(encoding="utf-8")
        # The two hand-written workflows dist was asked to call, in the phases
        # that make them mean something: the gate before anything is built,
        # the bill of materials before anything is attached.
        self.assertIn("./.github/workflows/release-gate.yml", workflow)
        self.assertIn("./.github/workflows/sbom.yml", workflow)
        # Every action dist writes comes from `[dist.github-action-commits]`,
        # so the generated workflow is held to the same rule as the rest.
        for uses in USES.findall(workflow):
            if uses.startswith("."):
                continue
            self.assertRegex(uses, r"@[0-9a-f]{40}$", f"{uses} is not pinned")

        # Generating must not rewrite the configuration it read. `dist init`
        # does exactly that — it normalises this file from its own template
        # and drops every comment — which is why the documented step is
        # `generate`, and why this asserts rather than trusts it.
        self.git(generated, "diff", "--exit-code", "--", "dist-workspace.toml")

        # And it is idempotent, which is what makes `--check` usable as the
        # signal that a configuration change was never regenerated.
        subprocess.run(["dist", "generate", "--check"], cwd=generated, check=True)

    def test_update_preserves_project_owned_edits(self) -> None:
        with tempfile.TemporaryDirectory() as source_dir, tempfile.TemporaryDirectory() as destination_dir:
            source = Path(source_dir)
            destination = Path(destination_dir)
            snapshot_without_git(source)

            self.git(source, "init", "--initial-branch=main")
            self.git(source, "config", "user.name", "Template Test")
            self.git(source, "config", "user.email", "template@example.invalid")
            self.git(source, "config", "commit.gpgsign", "false")
            self.git(source, "add", ".")
            self.git(source, "commit", "-m", "feat: initial template")
            self.git(source, "tag", "v1.0.0")

            arguments = []
            for question, answer in (
                ANSWERS | {"project_kind": "published_library"}
            ).items():
                arguments += ["--data", f"{question}={answer}"]
            subprocess.run(
                [
                    "copier",
                    "copy",
                    "--trust",
                    "--defaults",
                    *arguments,
                    str(source),
                    str(destination),
                ],
                check=True,
            )
            self.git(destination, "init", "--initial-branch=main")
            self.git(destination, "config", "user.name", "Project Test")
            self.git(destination, "config", "user.email", "project@example.invalid")
            self.git(destination, "config", "commit.gpgsign", "false")
            self.git(destination, "add", ".")
            self.git(destination, "commit", "-m", "feat: generate project")

            readme = destination / "README.md"
            readme.write_text(
                readme.read_text(encoding="utf-8") + "\nProject-owned note.\n",
                encoding="utf-8",
            )
            self.git(destination, "add", "README.md")
            self.git(destination, "commit", "-m", "docs: customize project")

            contributing = source / "template/CONTRIBUTING.md.jinja"
            contributing.write_text(
                contributing.read_text(encoding="utf-8") + "\nTemplate update marker.\n",
                encoding="utf-8",
            )
            self.git(source, "add", ".")
            self.git(source, "commit", "-m", "docs: update contribution guidance")
            self.git(source, "tag", "v1.1.0")

            subprocess.run(
                ["copier", "update", "--trust", "--defaults"],
                cwd=destination,
                check=True,
            )

            self.assertIn("Project-owned note.", readme.read_text(encoding="utf-8"))
            self.assertIn(
                "Template update marker.",
                (destination / "CONTRIBUTING.md").read_text(encoding="utf-8"),
            )

    def git(self, cwd: Path, *args: str) -> None:
        subprocess.run(["git", *args], cwd=cwd, check=True)


if __name__ == "__main__":
    unittest.main()
