from __future__ import annotations

import re
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

import yaml


TEMPLATE_ROOT = Path(__file__).resolve().parents[1]

# `uses:` as a YAML key, anchored to the start of its line. Unanchored, this
# also matches the pin check's own grep pattern, which is a shell string
# inside a `run:` block that happens to contain the word.
USES = re.compile(r"^\s*-?\s*uses:\s*(\S+)", re.MULTILINE)

# Every question the template asks, answered. The template carries no defaults
# — a default is an answer nobody gave — so a generation that omits one fails,
# and this suite answers every question like any other caller.
ANSWERS = {
    "project_name": "example-ui",
    "project_description": "An example package generated by the project template.",
    "github_owner": "example-owner",
    "keywords": "example, template",
    "categories": "development-tools",
    "rust_toolchain": "1.97.1",
    "rust_version": "1.92",
    "license_expression": "MIT",
    "copyright_holder": "Example Holder",
    "copyright_year": "2026",
    "unsafe_policy": "deny",
    # The strictest of the locales `typos` offers, for the same reason as the
    # surfaces below: it is the answer that gives the generated project's gate
    # something to enforce. `en` is what the dedicated test renders.
    "prose_locale": "en-us",
    "clippy_pedantic": "true",
    # A native dependency and the musl check are independent answers, and both
    # are answered yes here for the same reason as the surfaces below: yes is
    # the answer that generates something to check. The dedicated test renders
    # the other way round.
    "system_packages": "libfontconfig1-dev",
    "musl_check": "true",
    # Named rather than empty, because empty is the branch that renders the
    # same `--workspace` line the check has always had. The dedicated test
    # renders both.
    "musl_packages": "example-ui",
    # The opt-in verification surfaces, all on: the suite's job is to check
    # what the template can generate, and `yes` is the answer that generates
    # something to check. The opt-out is what the dedicated test renders.
    "openssf_scorecard": "true",
    "mutation_testing": "true",
    "fuzzing": "true",
}


def snapshot_without_git(destination: Path) -> Path:
    """Copies the template to `destination`, leaving `.git` behind.

    Copier reads a local template that is a Git repository at its latest tag,
    not as it sits on disk — correct for someone generating a project, and
    wrong for a test suite, which would then be checking the last release
    instead of the change being made. Without a `.git` directory there is no
    tag to prefer and Copier reads the files.

    `symlinks=True` because `AGENTS.md` is one, and the suite checks that it
    still is on the other side.
    """
    shutil.copytree(
        TEMPLATE_ROOT,
        destination,
        dirs_exist_ok=True,
        ignore=shutil.ignore_patterns(".git", "__pycache__"),
        symlinks=True,
    )
    return destination


class TemplateGenerationTests(unittest.TestCase):
    template: Path

    @classmethod
    def setUpClass(cls) -> None:
        cls._snapshot = tempfile.TemporaryDirectory()
        cls.addClassCleanup(cls._snapshot.cleanup)
        cls.template = snapshot_without_git(Path(cls._snapshot.name))

    def render(self, *, project_kind: str, **overrides: str) -> Path:
        temporary = tempfile.TemporaryDirectory()
        self._temporary_directories.append(temporary)
        self.addCleanup(temporary.cleanup)
        destination = Path(temporary.name)
        answers = ANSWERS | {"project_kind": project_kind} | overrides
        arguments = []
        for question, answer in answers.items():
            arguments += ["--data", f"{question}={answer}"]
        subprocess.run(
            [
                "copier",
                "copy",
                "--trust",
                "--defaults",
                *arguments,
                str(self.template),
                str(destination),
            ],
            check=True,
        )
        return destination

    def setUp(self) -> None:
        self._temporary_directories: list[tempfile.TemporaryDirectory[str]] = []

    def paths_in(self, generated: Path) -> set[str]:
        return {
            path.relative_to(generated).as_posix()
            for path in generated.rglob("*")
        }

    def test_published_library_exposes_the_approved_project_surface(self) -> None:
        generated = self.render(project_kind="published_library")
        expected_paths = {
            ".copier-answers.yml",
            ".github/dependabot.yml",
            ".github/workflows/ci.yml",
            ".github/workflows/commits.yml",
            ".github/workflows/dco.yml",
            ".github/workflows/minimal-versions.yml",
            ".github/workflows/msrv.yml",
            ".github/workflows/musl.yml",
            ".github/workflows/package.yml",
            ".github/workflows/release-plz.yml",
            ".github/workflows/release.yml",
            ".github/workflows/scorecard.yml",
            ".github/workflows/mutants.yml",
            ".github/workflows/semver.yml",
            ".github/workflows/security.yml",
            ".github/workflows/template-update.yml",
            ".editorconfig",
            "fuzz/Cargo.toml",
            "fuzz/fuzz_targets/api.rs",
            "fuzz/.gitignore",
            ".github/ISSUE_TEMPLATE/bug.yml",
            ".github/PULL_REQUEST_TEMPLATE.md",
            ".github/system-packages",
            ".gitignore",
            ".config/nextest.toml",
            "AGENTS.md",
            "CHANGELOG.md",
            "CLAUDE.md",
            "CONTRIBUTING.md",
            "Cargo.lock",
            "Cargo.toml",
            "LICENSE",
            "README.md",
            "SECURITY.md",
            "clippy.toml",
            "deny.toml",
            "fixtures/consumer/Cargo.toml",
            "fixtures/consumer/Cargo.lock",
            "fixtures/consumer/src/main.rs",
            "tests/public_api.rs",
            "release-plz.toml",
            "taplo.toml",
            "rust-toolchain.toml",
            "xtask/Cargo.toml",
            "xtask/src/main.rs",
        }

        self.assertTrue(expected_paths.issubset(self.paths_in(generated)))
        self.assertTrue((generated / "AGENTS.md").is_symlink())
        self.assertEqual((generated / "AGENTS.md").readlink(), Path("CLAUDE.md"))
        self.assertIn(
            'rust-version = "1.92"',
            (generated / "Cargo.toml").read_text(encoding="utf-8"),
        )

    def test_workspace_application_generates_runnable_app_and_xtask(self) -> None:
        generated = self.render(project_kind="workspace_app")

        self.assertTrue((generated / "apps/example-ui/src/main.rs").is_file())
        self.assertTrue((generated / "xtask/src/main.rs").is_file())
        self.assertFalse((generated / "src/lib.rs").exists())

        # What `dist generate` needs and cannot infer. Asserted on the manifest as
        # well as through dist itself, because the dist test skips wherever
        # dist is not installed and this is the half that explains why.
        manifest = (generated / "apps/example-ui/Cargo.toml").read_text(
            encoding="utf-8"
        )
        self.assertIn("repository.workspace = true", manifest)
        self.assertIn("dist = true", manifest)

        subprocess.run(
            ["cargo", "xtask", "check"],
            cwd=generated,
            check=True,
        )

    def test_a_generated_project_passes_its_own_gate(self) -> None:
        """`cargo xtask ci` is what a generated project asks of every change,
        including the first one. A template that hands a project a gate it
        cannot pass has handed it a problem to fix before it can start.

        This is where rendering shows: `cargo fmt --check` fails on a blank
        line a Jinja block left behind, and `cargo deny` fails on a member
        crate whose manifest names no license.
        """
        for project_kind in ("published_library", "workspace_app"):
            with self.subTest(project_kind=project_kind):
                generated = self.render(project_kind=project_kind)
                subprocess.run(
                    ["cargo", "xtask", "ci"],
                    cwd=generated,
                    check=True,
                )

                # And the feature and lint tasks again with a dev-dependency in
                # the tree: `cargo hack --no-dev-deps` hands cargo a manifest
                # without that table, and the flags beside it must tolerate the
                # re-resolve. The skeleton has no dev-dependencies, which is
                # exactly how an incompatible `--locked` once shipped
                # unnoticed. itoa, because it has none of its own.
                subprocess.run(
                    ["cargo", "add", "--dev", "itoa@1", "--package", "example-ui"],
                    cwd=generated,
                    check=True,
                )
                # Anchored where a dev-dependency is actually visible: an
                # integration test for the library, a `#[cfg(test)]` module
                # for the binary — `use` in plain binary code cannot see it.
                if project_kind == "published_library":
                    anchor, snippet = (
                        "tests/public_api.rs",
                        "\n// Anchors the dev-dependency for cargo-machete.\n"
                        "use itoa as _;\n",
                    )
                else:
                    anchor, snippet = (
                        "apps/example-ui/src/main.rs",
                        "\n// Anchors the dev-dependency for cargo-machete.\n"
                        "#[cfg(test)]\n"
                        "mod dev_dependency_anchor {\n"
                        "    use itoa as _;\n"
                        "}\n",
                    )
                with open(generated / anchor, "a", encoding="utf-8") as file:
                    file.write(snippet)
                for task in ("lint", "features"):
                    subprocess.run(
                        ["cargo", "xtask", task],
                        cwd=generated,
                        check=True,
                    )

    def test_the_fuzz_task_finds_every_fuzz_crate_and_stays_out_of_the_gate(
        self,
    ) -> None:
        """A fuzz crate is a workspace of its own — nightly and a sanitizer,
        deliberately outside the tree the gate compiles — so nothing else
        builds its targets, and a change to the API a target calls breaks it
        silently and stays broken. `cargo xtask fuzz` is what compiles them,
        and it finds them rather than being told where they are: `fuzz/` at
        the root, which the scaffold writes, and `crates/<name>/fuzz`, which a
        workspace grows by hand.

        Building a real target needs nightly and cargo-fuzz, which this suite
        does not require, so what is asserted here is the discovery: nothing
        found is a success, and a directory found is an attempt to build it —
        an attempt that fails, because these stubs are not crates.

        Compiling a target is a check; running one is a search. The search
        stays out of the gate and out of CI, which is the other half of this.
        """
        generated = self.render(project_kind="workspace_app")

        # The case most projects are in, and so the one that must not be
        # something to remember to ignore.
        subprocess.run(["cargo", "xtask", "fuzz"], cwd=generated, check=True)

        for planted, layout in (("fuzz", "fuzz"), ("crates/parser", "crates/parser/fuzz")):
            with self.subTest(layout=layout):
                stub = generated / layout / "Cargo.toml"
                stub.parent.mkdir(parents=True)
                stub.write_text("# Not a crate.\n", encoding="utf-8")
                # A crate under `crates/` is a workspace member, and one
                # without a manifest fails the workspace rather than the task
                # — which would pass this test for the wrong reason.
                if layout.startswith("crates/"):
                    (stub.parent.parent / "src").mkdir()
                    (stub.parent.parent / "src/lib.rs").write_text(
                        "", encoding="utf-8"
                    )
                    (stub.parent.parent / "Cargo.toml").write_text(
                        '[package]\nname = "parser"\n'
                        'version = "0.0.0"\nedition = "2024"\n'
                        'license = "MIT"\n',
                        encoding="utf-8",
                    )
                found = subprocess.run(
                    ["cargo", "xtask", "fuzz"],
                    cwd=generated,
                    capture_output=True,
                )
                shutil.rmtree(generated / planted)
                # The task's own words for a child that ran and failed, which
                # is what proves it stood in that directory and started one.
                self.assertIn(
                    "`cargo` exited with",
                    found.stderr.decode(),
                    f"`cargo xtask fuzz` did not look inside {layout}",
                )

        # Named where somebody looks for it, and nowhere it would run.
        usage = subprocess.run(["cargo", "xtask"], cwd=generated, capture_output=True)
        self.assertIn("fuzz", usage.stderr.decode())
        source = (generated / "xtask/src/main.rs").read_text(encoding="utf-8")
        self.assertNotIn('run("fuzz")', source)
        self.assertIn(
            "cargo xtask fuzz",
            (generated / "CONTRIBUTING.md").read_text(encoding="utf-8"),
        )
        for workflow in (generated / ".github/workflows").iterdir():
            self.assertNotIn(
                "xtask fuzz", workflow.read_text(encoding="utf-8"), str(workflow)
            )

    def test_all_supported_profile_combinations_render(self) -> None:
        for project_kind in ("published_library", "workspace_app"):
            for unsafe_policy in ("deny", "scoped"):
                for clippy_pedantic in ("true", "false"):
                    with self.subTest(
                        project_kind=project_kind,
                        unsafe_policy=unsafe_policy,
                        clippy_pedantic=clippy_pedantic,
                    ):
                        self.assert_profile_combination_renders(
                            project_kind, unsafe_policy, clippy_pedantic
                        )

    def assert_profile_combination_renders(
        self, project_kind: str, unsafe_policy: str, clippy_pedantic: str
    ) -> None:
        generated = self.render(
            project_kind=project_kind,
            unsafe_policy=unsafe_policy,
            clippy_pedantic=clippy_pedantic,
        )
        manifest = (generated / "Cargo.toml").read_text(encoding="utf-8")
        expected = "deny" if unsafe_policy == "deny" else "warn"
        self.assertIn(f'unsafe_code = "{expected}"', manifest)
        # Enabled whole or absent whole — the question the template asks is
        # about the group, never about individual pedantic lints.
        self.assertEqual(
            'pedantic = { level = "warn", priority = -1 }' in manifest,
            clippy_pedantic == "true",
        )
        # Miri answers a question only code allowed to write
        # `unsafe` can raise, and it costs an order of magnitude
        # in CI minutes to ask.
        self.assertEqual(
            (generated / ".github/workflows/miri.yml").exists(),
            unsafe_policy == "scoped",
        )
        # A library promises a minimum toolchain to whoever
        # depends on it; an application ships binaries and
        # promises nothing to a compiler. Each carries the release
        # path and checks that fit it, and neither the other's.
        library = project_kind == "published_library"
        paths = self.paths_in(generated)
        for path, belongs_to_a_library in (
            (".github/workflows/release.yml", True),
            (".github/workflows/msrv.yml", True),
            (".github/workflows/minimal-versions.yml", True),
            (".github/workflows/package.yml", True),
            ("fixtures/consumer/Cargo.toml", True),
            ("tests/public_api.rs", True),
            ("crates/README.md", False),
            # An application is the kind whose release workflow is generated
            # rather than written, and this is what tells actionlint not to
            # report dist's shell style as though somebody could fix it.
            (".github/actionlint.yaml", False),
            (".github/zizmor.yml", False),
            (".github/workflows/release-gate.yml", False),
            (".github/workflows/sbom.yml", False),
            (".github/workflows/dist-check.yml", False),
            ("dist-workspace.toml", False),
        ):
            self.assertEqual(
                path in paths,
                library == belongs_to_a_library,
                f"{path} in a {project_kind}",
            )

    def test_the_optional_verification_surfaces_are_opt_in(self) -> None:
        """Scorecard, mutation testing and fuzzing each cost something — CI
        minutes, a public score, a directory — so each is a question, and
        `no` has to mean the file is absent rather than present and off."""
        declined = self.paths_in(self.render(
            project_kind="published_library",
            openssf_scorecard="false",
            mutation_testing="false",
            fuzzing="false",
        ))
        for path in (
            ".github/workflows/scorecard.yml",
            ".github/workflows/mutants.yml",
            "fuzz/Cargo.toml",
        ):
            self.assertNotIn(path, declined)

        # Semver checking compares against the version on crates.io and a
        # fuzz harness exercises a public API — a workspace application has
        # neither, whatever the answers say.
        application = self.paths_in(self.render(project_kind="workspace_app"))
        self.assertNotIn(".github/workflows/semver.yml", application)
        self.assertNotIn("fuzz/Cargo.toml", application)
        self.assertIn(".github/workflows/scorecard.yml", application)
        self.assertIn(".github/workflows/mutants.yml", application)

    def test_the_prose_locale_is_the_answer_and_sits_with_the_typos_config(
        self,
    ) -> None:
        """`typos` applies its British-to-American mapping only when it is
        told a variant, so the answer is what makes a spelling a build
        failure. It goes in `Cargo.toml`, beside the exclude list: a
        `typos.toml` beside a manifest wins over `[workspace.metadata.typos]`
        outright rather than merging with it, so a second file would silently
        drop `target/` back into the check."""
        for answer in ("en-us", "en"):
            rendered = self.render(
                project_kind="published_library", prose_locale=answer
            )
            manifest = (rendered / "Cargo.toml").read_text()
            self.assertIn(
                f'[workspace.metadata.typos.default]\nlocale = "{answer}"',
                manifest,
            )
            self.assertNotIn("typos.toml", self.paths_in(rendered))

    def test_the_spelling_gate_reads_the_hidden_files_too(self) -> None:
        """`typos` walks a directory the way a search tool does: hidden paths
        are skipped unless it is told otherwise, which would leave the whole
        of `.github/` — the workflows, the composite action, the issue
        templates — out of the only check that reads their prose. Asserted by
        asking typos what it would read, rather than by reading back the
        setting that is supposed to cause it.

        `target/` and `.git/` stay out: the first is build output, the second
        is compressed objects and a reflog quoting subjects the project may
        since have corrected.
        """
        rendered = self.render(project_kind="published_library")
        listed = subprocess.run(
            ["typos", "--files"],
            cwd=rendered,
            check=True,
            capture_output=True,
            text=True,
        ).stdout
        # typos prints its paths relative to the directory it walked, which
        # is the generated project rather than this suite's own.
        read = {
            (rendered / line).resolve().relative_to(rendered.resolve()).as_posix()
            for line in listed.splitlines()
            if line
        }

        self.assertIn(".github/workflows/ci.yml", read)
        self.assertIn(".github/actions/rust/action.yml", read)
        self.assertIn(".github/ISSUE_TEMPLATE/bug.yml", read)
        self.assertIn(".config/nextest.toml", read)
        self.assertIn(".cargo/config.toml", read)
        self.assertFalse({path for path in read if path.startswith(".git/")})

    def test_native_dependencies_are_declared_once_and_musl_is_optional(
        self,
    ) -> None:
        """A native dependency is named in one file every CI job reads, rather
        than as an argument each workflow repeats — eight call sites is eight
        merge conflicts on the next `copier update`.

        And musl is a question, because it is one a project can be unable to
        answer: a dependency linked through `pkg-config` cannot be
        cross-compiled against libraries installed for the runner's own
        architecture, so the job would be permanently red rather than
        informative.
        """
        declared = self.render(project_kind="workspace_app")
        self.assertIn(
            "libfontconfig1-dev",
            (declared / ".github/system-packages").read_text(encoding="utf-8"),
        )

        declined = self.render(
            project_kind="workspace_app",
            system_packages="",
            musl_check="false",
        )
        paths = self.paths_in(declined)
        self.assertNotIn(".github/system-packages", paths)
        self.assertNotIn(".github/workflows/musl.yml", paths)
        # And dist ships what CI compiles: no musl job, no musl binaries.
        configuration = (declined / "dist-workspace.toml").read_text(
            encoding="utf-8"
        )
        self.assertNotIn("musl", configuration)
        self.assertIn(
            "x86_64-unknown-linux-musl",
            (declared / "dist-workspace.toml").read_text(encoding="utf-8"),
        )

    def test_the_musl_check_covers_the_packages_the_answer_names(self) -> None:
        """A workspace is not always uniformly portable: one binary can be the
        one that ships statically linked while another pulls in a dependency
        with no musl build at all, and a whole-workspace check there is red
        for a reason nobody intends to fix. Empty stays `--workspace`, which
        is what a project with nothing to exclude should keep."""
        scoped = self.render(project_kind="workspace_app", musl_packages="example-ui")
        self.assertIn("example-ui", (scoped / ".github/musl-packages").read_text())

        whole = self.render(project_kind="workspace_app", musl_packages="")
        self.assertEqual(
            (whole / ".github/musl-packages").read_text().strip().splitlines()[-1][:1],
            "#",
        )

        # And absent altogether where the check itself is, so that the pair is
        # excluded together rather than leaving a scope for a workflow nobody
        # generated.
        declined = self.paths_in(
            self.render(project_kind="workspace_app", musl_check="false")
        )
        self.assertNotIn(".github/workflows/musl.yml", declined)
        self.assertNotIn(".github/musl-packages", declined)

    def test_the_gate_reads_the_manifests_the_spell_checker_skips(self) -> None:
        """`typos` carries a built-in `lock` file type with checking switched
        off, and its glob list has `Cargo.toml` in it beside `Cargo.lock` — so
        walking the tree never reads a manifest, and for a published crate the
        `description` it skips is the text on the registry page.

        No configuration turns this back on: the built-in type wins over a
        `[type]` table naming the same glob, and re-enabling `lock` itself
        would take every lockfile with it. Standard input is the way past it,
        which is what `lint` does — asserted by planting a misspelling and
        watching the gate reject it, rather than by reading the code back.
        """
        # Transposed here rather than written out, because this repository's
        # own spelling gate reads this file and would reject the literal.
        misspelling = "example".replace("am", "ma", 1)
        rendered = self.render(project_kind="published_library")
        manifest = rendered / "Cargo.toml"
        manifest.write_text(
            manifest.read_text().replace(
                "An example package", f"An {misspelling} package", 1
            ),
            encoding="utf-8",
        )
        lint = subprocess.run(
            ["cargo", "xtask", "lint"],
            cwd=rendered,
            capture_output=True,
            text=True,
        )
        self.assertNotEqual(lint.returncode, 0)
        self.assertIn(misspelling, lint.stdout + lint.stderr)

    def test_the_gate_reaches_the_consumer_fixture_outside_the_workspace(
        self,
    ) -> None:
        """The fixture has to be its own workspace to depend on this crate the
        way a stranger does, which is exactly why `--all` and `--workspace`
        stop at its boundary — so the template ships a Rust file its own gate
        cannot see unless something stands inside the directory. `lint`
        formats it; `package` lints it, where the build it needs is already
        being paid for.
        """
        rendered = self.render(project_kind="published_library")
        fixture = rendered / "fixtures/consumer/src/main.rs"
        original = fixture.read_text()

        fixture.write_text(original.replace("fn main() {", "fn  main( ) {", 1))
        formatting = subprocess.run(
            ["cargo", "xtask", "lint"],
            cwd=rendered,
            capture_output=True,
            text=True,
        )
        self.assertNotEqual(formatting.returncode, 0)

        # Formatted the way rustfmt wants it, so only clippy is left to object.
        # Appended before the closing brace of `main` rather than at the first
        # `}`, which belongs to the format string.
        fixture.write_text(f"{original.rstrip()[:-1]}    return;\n}}\n")
        linting = subprocess.run(
            ["cargo", "xtask", "package"],
            cwd=rendered,
            capture_output=True,
            text=True,
        )
        self.assertNotEqual(linting.returncode, 0)
        self.assertIn("needless_return", linting.stdout + linting.stderr)

    def test_the_license_files_are_the_ones_the_expression_names(self) -> None:
        """A project carries the text of every license it offers, and no other.

        The SPDX expression in `Cargo.toml` is a promise about what a user may
        do; the files beside it are what they read to find out. One without the
        other is a project that cannot be used by anyone who checks.

        A single license is `LICENSE` — the name a reader and every tool looks
        for. Two have to be told apart, and only then are they spelled out.
        """
        mit_only = self.paths_in(self.render(
            project_kind="published_library",
            license_expression="MIT",
        ))
        self.assertIn("LICENSE", mit_only)
        self.assertNotIn("LICENSE-MIT", mit_only)
        self.assertNotIn("LICENSE-APACHE-2.0", mit_only)

        apache_only = self.render(
            project_kind="published_library",
            license_expression="Apache-2.0",
        )
        self.assertIn("LICENSE", self.paths_in(apache_only))
        self.assertNotIn("LICENSE-MIT", self.paths_in(apache_only))
        self.assertIn(
            "Apache License",
            (apache_only / "LICENSE").read_text(encoding="utf-8"),
        )

        dual = self.render(
            project_kind="workspace_app",
            license_expression="MIT OR Apache-2.0",
        )
        self.assertIn("LICENSE-MIT", self.paths_in(dual))
        self.assertIn("LICENSE-APACHE-2.0", self.paths_in(dual))
        self.assertNotIn("LICENSE", self.paths_in(dual))
        self.assertIn(
            "Copyright (c) 2026 Example Holder",
            (dual / "LICENSE-MIT").read_text(encoding="utf-8"),
        )
        self.assertIn(
            'license = "MIT OR Apache-2.0"',
            (dual / "Cargo.toml").read_text(encoding="utf-8"),
        )

    def test_nothing_generated_still_contains_jinja(self) -> None:
        """A file holding `{{ ... }}` without a `.jinja` suffix is copied
        verbatim, and the project is generated with the placeholder still in
        it. Nothing else notices: the file is valid YAML, valid Markdown, and
        wrong — an issue form linking to `github.com/owner/{{ project_name }}`
        renders and is simply a dead link.

        `${{ ... }}` is GitHub Actions' own syntax and belongs in workflows.
        """
        for project_kind in ("published_library", "workspace_app"):
            generated = self.render(project_kind=project_kind)
            for path in sorted(generated.rglob("*")):
                if not path.is_file() or path.is_symlink():
                    continue
                try:
                    text = path.read_text(encoding="utf-8")
                except UnicodeDecodeError:
                    continue
                leftovers = [
                    line
                    for line in text.splitlines()
                    if ("{{" in line.replace("${{", "") or "{%" in line)
                ]
                self.assertEqual(
                    leftovers,
                    [],
                    f"{path.relative_to(generated)} was copied without being rendered",
                )

    def test_generated_workflows_survive_the_checks_they_ship_with(self) -> None:
        """The workflows are shipped as text and never run before a project has
        them, so nothing here would notice a broken one until a real repository
        did. Both tools the generated `Workflow syntax` job runs are run here,
        against the same tree, with the same flags.

        An application's `.github/workflows/release.yml` is written by `dist
        generate`, not shipped — so checking a project as generated checks
        every workflow except the one nobody wrote, which is the one whose
        style is not ours to fix. Generating it first is what makes this the
        same question a real repository asks, and what the two ignore files
        beside it exist to answer.

        Each half skips rather than fails where its tool is absent: the
        template's own CI installs both, and a contributor without them should
        still be able to run the suite.
        """
        if shutil.which("actionlint") is None and shutil.which("zizmor") is None:
            self.skipTest("neither actionlint nor zizmor is installed")

        for project_kind in ("published_library", "workspace_app"):
            with self.subTest(project_kind=project_kind):
                generated = self.render(project_kind=project_kind)
                # Both want a repository: actionlint to resolve `./`-relative
                # actions and the default branch, zizmor to know what it is
                # auditing.
                self.git(generated, "init", "--initial-branch=main")
                if project_kind == "workspace_app" and shutil.which("dist"):
                    self.generate_release_workflow(generated)
                if shutil.which("actionlint"):
                    subprocess.run(["actionlint"], cwd=generated, check=True)
                if shutil.which("zizmor"):
                    subprocess.run(
                        [
                            "zizmor",
                            "--persona=regular",
                            "--min-severity=medium",
                            "--min-confidence=medium",
                            # Offline: the audits that ask GitHub about an
                            # action's tags need a token this suite has no
                            # business holding, and their findings are about
                            # pins rather than about the template.
                            "--offline",
                            ".",
                        ],
                        cwd=generated,
                        check=True,
                    )

    def test_every_action_in_a_generated_project_is_pinned_to_a_commit(self) -> None:
        """A tag is a name the publisher can move; a commit is not.

        The generated project runs this check on itself, which is the point at
        which an unpinned action is found — in somebody else's repository,
        after they generated it. Ask here instead.
        """
        pinned = re.compile(r"@[0-9a-f]{40}$")
        for project_kind in ("published_library", "workspace_app"):
            with self.subTest(project_kind=project_kind):
                generated = self.render(project_kind=project_kind)
                for path in sorted((generated / ".github").rglob("*.yml")):
                    for uses in USES.findall(path.read_text(encoding="utf-8")):
                        # Local actions are this repository's own and carry no
                        # `@ref` to pin.
                        if uses.startswith("."):
                            continue
                        self.assertRegex(
                            uses,
                            pinned,
                            f"{path.relative_to(generated)} pins {uses} to a tag",
                        )

    def test_a_workspace_application_can_generate_its_release_workflow(self) -> None:
        """`dist generate` is a setup step the generated project cannot skip:
        it is what turns dist-workspace.toml into the workflow that reads it,
        and until it runs the project has a release configuration and nothing
        that runs it.

        Two things make it fail on a project nothing has touched, and both are
        invisible until somebody tries. `publish = false` says nothing goes to
        a registry, and dist reads it as "not worth building" — leaving a
        release with no binaries. And dist wants each binary's own manifest to
        name the repository, which a `[workspace.package]` entry reaches only
        where the member asks for it.

        Skipped rather than failed where dist is absent, so a contributor
        without it can still run the suite; this repository's CI installs it.
        """
        if shutil.which("dist") is None:
            self.skipTest("dist is not installed")

        generated = self.render(project_kind="workspace_app")
        # dist reads the workspace through git, and writes into `.github/`.
        self.git(generated, "init", "--initial-branch=main")
        release = self.generate_release_workflow(generated)
        self.assertTrue(release.is_file(), "dist generate wrote no workflow")
        workflow = release.read_text(encoding="utf-8")
        # The two hand-written workflows dist was asked to call, in the phases
        # that make them mean something: the gate before anything is built,
        # the bill of materials before anything is attached.
        self.assertIn("./.github/workflows/release-gate.yml", workflow)
        self.assertIn("./.github/workflows/sbom.yml", workflow)
        # Every action dist writes comes from `[dist.github-action-commits]`,
        # so the generated workflow is held to the same rule as the rest.
        for uses in USES.findall(workflow):
            if uses.startswith("."):
                continue
            self.assertRegex(uses, r"@[0-9a-f]{40}$", f"{uses} is not pinned")

        # Generating must not rewrite the configuration it read. `dist init`
        # does exactly that — it normalizes this file from its own template
        # and drops every comment — which is why the documented step is
        # `generate`, and why this asserts rather than trusts it.
        self.git(generated, "diff", "--exit-code", "--", "dist-workspace.toml")

        # And it is idempotent, which is what makes `--check` usable as the
        # signal that a configuration change was never regenerated.
        subprocess.run(["dist", "generate", "--check"], cwd=generated, check=True)

    def test_update_preserves_project_owned_edits(self) -> None:
        with tempfile.TemporaryDirectory() as source_dir, tempfile.TemporaryDirectory() as destination_dir:
            source = Path(source_dir)
            destination = Path(destination_dir)
            snapshot_without_git(source)

            self.git(source, "init", "--initial-branch=main")
            self.git(source, "config", "user.name", "Template Test")
            self.git(source, "config", "user.email", "template@example.invalid")
            self.git(source, "config", "commit.gpgsign", "false")
            self.git(source, "add", ".")
            self.git(source, "commit", "-m", "feat: initial template")
            self.git(source, "tag", "v1.0.0")

            arguments = []
            for question, answer in (
                ANSWERS | {"project_kind": "published_library"}
            ).items():
                arguments += ["--data", f"{question}={answer}"]
            subprocess.run(
                [
                    "copier",
                    "copy",
                    "--trust",
                    "--defaults",
                    *arguments,
                    str(source),
                    str(destination),
                ],
                check=True,
            )
            self.git(destination, "init", "--initial-branch=main")
            self.git(destination, "config", "user.name", "Project Test")
            self.git(destination, "config", "user.email", "project@example.invalid")
            self.git(destination, "config", "commit.gpgsign", "false")
            self.git(destination, "add", ".")
            self.git(destination, "commit", "-m", "feat: generate project")

            readme = destination / "README.md"
            readme.write_text(
                readme.read_text(encoding="utf-8") + "\nProject-owned note.\n",
                encoding="utf-8",
            )
            self.git(destination, "add", "README.md")
            self.git(destination, "commit", "-m", "docs: customize project")

            contributing = source / "template/CONTRIBUTING.md.jinja"
            contributing.write_text(
                contributing.read_text(encoding="utf-8") + "\nTemplate update marker.\n",
                encoding="utf-8",
            )
            self.git(source, "add", ".")
            self.git(source, "commit", "-m", "docs: update contribution guidance")
            self.git(source, "tag", "v1.1.0")

            subprocess.run(
                ["copier", "update", "--trust", "--defaults"],
                cwd=destination,
                check=True,
            )

            self.assertIn("Project-owned note.", readme.read_text(encoding="utf-8"))
            self.assertIn(
                "Template update marker.",
                (destination / "CONTRIBUTING.md").read_text(encoding="utf-8"),
            )

    def test_update_survives_an_answers_file_written_before_a_question(
        self,
    ) -> None:
        """Every project generated before a question was added has an answers
        file without it, and `copier update` renders `_exclude` against exactly
        that file. An entry naming the answer directly raises `UndefinedError`
        and the update dies — in every existing project at once, at the one
        moment the template is meant to be doing its job.

        Which is why each `_exclude` entry reading an answer reads it through
        `| default`. This drops the two most recently added answers to check
        that it does; a question added to `_exclude` later belongs in this
        list.
        """
        added_since = ("system_packages", "musl_check")
        with tempfile.TemporaryDirectory() as source_dir, tempfile.TemporaryDirectory() as destination_dir:
            source = Path(source_dir)
            destination = Path(destination_dir)
            snapshot_without_git(source)

            # v1.0.0 is this template as it was before the two questions: no
            # question, no exclusion reading one, and none of the files those
            # exclusions decide. Rebuilt rather than checked out, so the test
            # keeps working when the previous release is no longer the one
            # these questions arrived after.
            configuration = source / "copier.yml"
            current = configuration.read_text(encoding="utf-8")
            before = yaml.safe_load(current)
            for question in added_since:
                del before[question]
            before["_exclude"] = [
                exclusion
                for exclusion in before["_exclude"]
                if not any(question in exclusion for question in added_since)
            ]
            configuration.write_text(yaml.safe_dump(before), encoding="utf-8")
            for path in (
                "template/.github/system-packages.jinja",
                "template/.github/workflows/musl.yml",
            ):
                (source / path).unlink()

            self.git(source, "init", "--initial-branch=main")
            self.git(source, "config", "user.name", "Template Test")
            self.git(source, "config", "user.email", "template@example.invalid")
            self.git(source, "config", "commit.gpgsign", "false")
            self.git(source, "add", ".")
            self.git(source, "commit", "-m", "feat: initial template")
            self.git(source, "tag", "v1.0.0")

            arguments = []
            for question, answer in (
                ANSWERS | {"project_kind": "workspace_app"}
            ).items():
                if question in added_since:
                    continue
                arguments += ["--data", f"{question}={answer}"]
            subprocess.run(
                [
                    "copier",
                    "copy",
                    "--trust",
                    "--defaults",
                    *arguments,
                    str(source),
                    str(destination),
                ],
                check=True,
            )

            self.git(destination, "init", "--initial-branch=main")
            self.git(destination, "config", "user.name", "Project Test")
            self.git(destination, "config", "user.email", "project@example.invalid")
            self.git(destination, "config", "commit.gpgsign", "false")
            self.git(destination, "add", ".")
            self.git(destination, "commit", "-m", "feat: generate project")

            # And v1.1.0 is the template as it stands, questions and all.
            configuration.write_text(current, encoding="utf-8")
            for path in (
                "template/.github/system-packages.jinja",
                "template/.github/workflows/musl.yml",
            ):
                shutil.copy2(TEMPLATE_ROOT / path, source / path)
            self.git(source, "add", ".")
            self.git(source, "commit", "-m", "feat: ask what the runners need")
            self.git(source, "tag", "v1.1.0")
            subprocess.run(
                [
                    "copier",
                    "update",
                    "--trust",
                    "--defaults",
                    "--data",
                    "system_packages=libfontconfig1-dev",
                    "--data",
                    "musl_check=false",
                ],
                cwd=destination,
                check=True,
            )

            # The answers arrived, and the files they decide followed them.
            self.assertIn(
                "libfontconfig1-dev",
                (destination / ".github/system-packages").read_text(encoding="utf-8"),
            )
            self.assertFalse((destination / ".github/workflows/musl.yml").exists())

    def git(self, cwd: Path, *args: str) -> None:
        subprocess.run(["git", *args], cwd=cwd, check=True)

    def generate_release_workflow(self, generated: Path) -> Path:
        """Runs `dist generate` in an already-initialized repository.

        dist reads the workspace through git and refuses a tree it cannot
        describe, so the commit is part of the step rather than setup for it.
        """
        self.git(generated, "config", "user.name", "Project Test")
        self.git(generated, "config", "user.email", "project@example.invalid")
        self.git(generated, "config", "commit.gpgsign", "false")
        self.git(generated, "add", ".")
        self.git(generated, "commit", "-m", "feat: generate project")
        subprocess.run(["dist", "generate"], cwd=generated, check=True)
        return generated / ".github/workflows/release.yml"


if __name__ == "__main__":
    unittest.main()
